### PR TITLE
add cvar to always get an overbounce

### PR DESCRIPTION
**Pull request by ovska**
- add cheat protected toggle cvar `etj_forceOb`
- add forced OB handling for DrawOB and OBwatcher
- clean up some checks for combined worldspawn/surfaceparm settings (`nooverbounce` and `nofalldamage`)

### CODE REVIEW

**Comment by Aciz** [comment]
This is not perfect, there are some minor prediction issues here and there, such as loading on angled surfaces and toggling the cvar just before load.

**Comment by ovska** [comment]
> This is not perfect, there are some minor prediction issues here and there, such as loading on angled surfaces and toggling the cvar just before load.

Probably need to do some extra handling to ignore the handler if teleported (or loaded) on last frame

**Comment by ovska** [comment]
There are still some lingering prediction errors when loading (and probably when teleporting too) to irregular surfaces (slopes or near brush edges). I'll need to look a little deeper, not merge ready yet

**Comment by ovska** [comment]
So far haven't gotten this to work with the quirks of SlideMove.

**Pull request closed without merging**
