### PR TITLE
feature: Simple snaphud

### PR DESCRIPTION
**Pull request by numbfingies**
gets rid of small snap zones

### CODE REVIEW

**Comment by Aciz** [comment]
Please rebase.

**Comment by Aciz** [comment]
I must say that I also really do not see the point of this, why would you want to do this? What benefit does it bring?

**Comment by numbfingies** [comment]
> I must say that I also really do not see the point of this, why would you want to do this? What benefit does it bring?

This helps to see zones by their impact on advancing 'forwards'. Essentialy, this removes small snap zones and simplifies HUD.
This feature needs more work. Converting to draft

**Comment by Aciz** [comment]
> > I must say that I also really do not see the point of this, why would you want to do this? What benefit does it bring?
> 
> This helps to see zones by their impact on advancing 'forwards'. Essentialy, this removes small snap zones and simplifies HUD.

But it does still show small zones though, when highlighting is enabled?

image

I just don't see how this benefits anyone, if you are hiding the zones, you are essentially giving incorrect information to the user, as they would instinctively aim to the end of a zone, but now this is actually incorrect as you're aiming at an "invisible" zone that is not optimal for accel.

**Pull request closed without merging**
