### PR TITLE
Use RelWithDebInfo build type for release pipeline

### PR DESCRIPTION
**Pull request by suburbski**
Allows debugging the etjump dev server, should be reverted before release

### CODE REVIEW

**Comment by Aciz** [comment]
Need to remember to turn this off for actual releases, but good to have for now.

**Comment by isRyven** [comment]
As far as i know, there isn't much use in that alone, `msvc` doesn't injects debug symbols into the executables / dlls, but rather stores them in `pdb` files, but in this case, `pdbs` are going to be left in azure's host environment. You probably need to ensure pdbs are included along with pk3 or such.

**Comment by Aciz** [comment]
Linux encodes them in .so files though, right? So at least this will help debug stuff on Linux (which is what prompted @suburbski to do this, he keeps crashing on bounce_b2 on dev server, and can't reproduce it locally).

**Comment by isRyven** [comment]
yeah linux should be good, we should still allow symbols for qagame in future, as far as i remember i did set the debug flag for qagame in old cmake project

**Comment by Aciz** [comment]
`pdb` files are now included for debugging on Windows too.

**Pull request merged**
